### ISSUE TITLE
$pubsub->listen can not be used in the startup

### ISSUE THREAD

**Issue by JianleiZhang** [kraih/mojo-pg#28] opened 2016-08-09 15:45 UTC
* Mojo::Pg version: 2.28
* Perl version: v5.20.2
* Operating system: Debian and kernel 3.16.7

### Steps to reproduce the behavior
cann't use $pubsub->listen in startup:

```perl
sub startup {
  my $self = shift;
  $self->helper(pg => sub {state $pg = Mojo::Pg->new('postgresql:///db')});
    $self->pg->pubsub->listen(
    permission => sub {
      my ($pubsub, $payload) = @_;
      $self->get_permission_cache;
    });
...
}
```

However, such this statement in the help is the performance of normal:
```perl
$self->attr('permission');
  $self->helper(
    get_permission_cache => sub {
      $self->{permission} = {};
      Mojo::IOLoop->delay(
	sub {
	  my $delay = shift;
	  my $sql   = "SELECT roles.id,key FROM roles " .
	              "JOIN permissions ON permissions.id = ANY(roles.permissions)";
	  $self->pg->db->query($sql, $delay->begin);
	},
	sub {
	  my ($delay, $err, $result) = @_;
	  if ($err or not $result->rows){
	    # 考虑是否退出?
	  }
	  foreach ($result->hash){
	    $self->{permission}->{$_->{key}}->{$_->{id}} = 1;
	  }

	  $self->pg->pubsub->unlisten('permission');
	  $self->pg->pubsub->listen(
	    permission => sub {
	      my ($pubsub, $payload) = @_;
	      $self->get_permission_cache;
	    });
	});
    });
```

**Comment by jberger** [comment] 2016-08-09 15:47
updated formatting

**Comment by jberger** [comment] 2016-08-09 15:49
I don't understand the problem. Certainly `listen` does work in the startup method

**Comment by jberger** [comment] 2016-08-09 17:14
Until you have more details this has to be closed as not reproducible. It may be reopened with more details or a running example.

**Closed by jberger** 2016-08-09 17:14 UTC

**Comment by jberger** [comment] 2016-08-09 17:20
For the record, the pubsub system only works while the loop is running, so I guess I should say, `listen` works but you won't see any results until the loop starts; which happens after startup completes. In your delay example, you might try adding ->wait to the end to make it portable between before and after the loop starts.

**Comment by JianleiZhang** [comment] 2016-08-10 01:28
I have a few tests:


Test 1)

```perl
sub startup {
  my $self = shift;
  $self->config(hypnotoad => {workers => 4});
  $self->helper(
    pg => sub {
      state $pg = Mojo::Pg->new('postgresql:///db')});

  $self->pg->pubsub->listen(
    cache => sub {
      my ($pubsub, $payload) = @_;
      $self->log->info($payload);
    });
}
```

Try to send a notify in other controller.
```perl
  $self->pg->pubsub->notify(cache => 'update!');
```

Nothing happens.


Test 2)

```perl
  $self->pg->pubsub->on(
    reconnect => sub {
      my ($pubsub, $db) = @_;
      $pubsub->listen(
	cache => sub {
	  my ($pubsub, $payload) = @_;
	  $self->log->info($payload);
	});
    });
```

Only one info contain the $payload when send notify once.


Test 3)

```perl
  $self->helper(
    test_pubsub => sub {
      Mojo::IOLoop->delay(
	sub {
	  my $delay = shift;
	  my $sql   = 'SELECT 1 + 1';
	  $self->pg->db->query($sql, $delay->begin);
	},
	sub {
	  $self->pg->pubsub->unlisten('cache');
	  $self->pg->pubsub->listen(
	    cache => sub {
	      my ($pubsub, $payload) = @_;
	      $self->log->info($payload);
	    });
	});
    });

  $self->test_pubsub;
```

4 info contain the $payload, maybe from the 4 workers.

This is what I need.


also test redis pub/sub
```perl
sub startup {
  my $self = shift;
  $self->config(hypnotoad => {workers => 4});
  $self->helper(redis => sub {state $redis = Mojo::Redis2->new()});
  
  $self->redis->subscribe(['cache']);
  $self->redis->on(
    message => sub {
      my (undef, $message, $channel) = @_;
      if ($channel eq 'cache'){
      	$self->log->info($message);
      }
    });
}
```

Only 3 info contain the $message, I don't know why.

**Comment by kraih** [comment] 2016-08-10 10:29
There is fork-safety code in `Mojo::Pg::PubSub` (https://github.com/kraih/mojo-pg/blob/master/lib/Mojo/Pg/PubSub.pm#L31), so this might be a bug if that code doesn't work. Afraid i don't have time to take a closer look at it now.

**Comment by kraih** [comment] 2016-08-10 12:35
There were bugs, but the behavior described here is intended i'm afraid. I've added a note to the docs. https://github.com/kraih/mojo-pg/commit/74d26c4d6160717caa0c2f39332ac892bbf779ca
